### ISSUE TITLE
EOL marker too dark.

### ISSUE THREAD

**Issue by wwalker** [bignimbus/pop-punk.vim#3]
First off, Awesome color scheme!!

For me, the EOL marker ( `?` ) in `list` mode is too dark.

When I do `set list` , I really want to see those.

I changed it to yellow in my fork.

Maybe something a little brighter?

**Comment by bignimbus** [comment]
Thanks for raising this. I will take a look sometime soon and see what can be done!

**Comment by bignimbus** [comment]
@wwalker try the `experimental` branch. I made a different color choice than you, but it's definitely higher contrast than the version in the main branch.

**Comment by bignimbus** [comment]
Latest merge to master addresses some contrast issues related to non-text characters.
